version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8011:8011"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/pluglr_auth
      - SPRING_DATASOURCE_USERNAME=pluglr_admin
      - SPRING_DATASOURCE_PASSWORD=Rubies@2030!
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      mysql_db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pluglr-springboot-network  

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pluglr_auth
      MYSQL_USER: pluglr_admin
      MYSQL_PASSWORD: Rubies@2030!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - pluglr-springboot-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    networks:
      - pluglr-springboot-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pluglr-springboot-network  

volumes:
  mysql_data:

networks:
  pluglr-springboot-network:   
    name: pluglr-springboot-network
    driver: bridge
