server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pluglr_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


file:
  upload-dir: src/main/resources/static/image

web:
    resources:
      static-locations: classpath:/static/

auth-service:
  base-url: https://api.pluglr.com

redis:
  host: localhost
  port: 6379

main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: DEBUG
