# Generated by Django 4.1 on 2025-03-26 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('startTime', models.CharField(max_length=255)),
                ('startYear', models.CharField(max_length=255)),
                ('endTime', models.CharField(max_length=255)),
                ('endYear', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('event_title', models.TextField(blank=True, null=True)),
                ('theme', models.ImageField(blank=True, null=True, upload_to='uploads/themes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
