# Generated by Django 4.2 on 2025-04-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customuser_eventschedule_accountverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AccountVerification',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
